services:
  daily-bot:
    container_name: daily-bot
    image: "ghcr.io/${REPO_NAME}:${BRANCH_NAME}"
    build:
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - .env:/usr/src/app/.env:ro
    env_file:
      - .env
