version: '3.8'

services:
  daily-bot:
    container_name: daily-bot
    image: "ghcr.io/${REPO_NAME}:${BRANCH_NAME}"
    build:
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      NODE_ENV: ${{ NODE_ENV }}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      OPENAI_API_KEY: ${{ OPENAI_API_KEY }}
      DISCORD_MAX_MESSAGE_LENGTH: ${{ DISCORD_MAX_MESSAGE_LENGTH }}
      DISCORD_API_REQ_LIMIT: ${{ DISCORD_API_REQ_LIMIT }}
      GUILD_ID: ${{ GUILD_ID }}
      CHANNELS_IDS: ${{ CHANNELS_IDS }}
      DAYJS_LOCALE: ${{ DAYJS_LOCALE }}
      RESULT_LANGUAGE: ${{ RESULT_LANGUAGE }}
      GPT_MODEL: ${{ GPT_MODEL }}
      GPT_TOKEN_COST: ${{ GPT_TOKEN_COST }}
      GPT_TIMEOUT_MS: ${{ GPT_TIMEOUT_MS }}
      GPT_TEMPERATURE: ${{ GPT_TEMPERATURE }}
      GPT_MODEL_TOKENS: ${{ GPT_MODEL_TOKENS }}
      GPT_COMPLETION_TOKENS: ${{ GPT_COMPLETION_TOKENS }}
      GPT_MIN_TOKENS_TO_ANALYZE: ${{ GPT_MIN_TOKENS_TO_ANALYZE }}
