version: '3.3'
services:
    daily-bot:
        container_name: daily-bot
        image: daily-bot
        build:
            context: ""
            dockerfile: Dockerfile
        restart: unless-stopped
        env_file: .env
