version: '3.8'

services:
  daily-bot:
    container_name: daily-bot
    image: "ghcr.io/${REPO_NAME}:${BRANCH_NAME}"
    build:
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV
      - DISCORD_TOKEN
      - OPENAI_API_KEY
      - DISCORD_MAX_MESSAGE_LENGTH
      - DISCORD_API_REQ_LIMIT
      - GUILD_ID
      - CHANNELS_IDS
      - DAYJS_LOCALE
      - RESULT_LANGUAGE
      - GPT_MODEL
      - GPT_TOKEN_COST
      - GPT_TIMEOUT_MS
      - GPT_TEMPERATURE
      - GPT_MODEL_TOKENS
      - GPT_COMPLETION_TOKENS
      - GPT_MIN_TOKENS_TO_ANALYZE
