version: '3.8'

services:
    daily-bot:
        container_name: daily-bot
        image: "ghcr.io/${REPO_NAME}:${BRANCH_NAME}"
        build:
            dockerfile: Dockerfile
        restart: unless-stopped
        environment:
          DISCORD_TOKEN: ${DISCORD_TOKEN}
          OPENAI_API_KEY: ${OPENAI_API_KEY}
          GUILD_ID: ${GUILD_ID}
          CHANNELS_IDS: ${CHANNELS_IDS}
          DAYJS_LOCALE: ${DAYJS_LOCALE}
          RESULT_LANGUAGE: ${RESULT_LANGUAGE}
