name: Deployment

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: deploy
      url: https://github.com
    steps:

      # UTILITIES
      - name: Extract branch name
        id: extract-branch
        run: echo ::set-output name=branch-name::$(basename "${{ github.ref }}")
      - name: Lowercase repo name
        id: lowercase-repo
        run: echo ::set-output name=lowercase-name::$(echo "${{ github.repository }}" | awk '{print tolower($0)}')

      # GENERAL
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ env.REPO_NAME }}:${{ env.BRANCH_NAME }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
        env:
          REPO_NAME: ${{ steps.lowercase-repo.outputs.lowercase-name }}
          BRANCH_NAME: ${{ steps.extract-branch.outputs.branch-name }}

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ vars.SSH_PATH }}
            export BRANCH_NAME=$(basename "${{ github.ref }}")
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker compose pull
            docker compose up -d

      #         Temp fix
      #         https://github.com/docker/build-push-action/issues/252
      #         https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

